- name: maven setup
  ansible.builtin.import_role:
    name: common
    tasks_from: maven-setup

- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: Install dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: mongo schema setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mysql-schema

- name: systemd setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup
    