- name: configuring rabbitmq repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash ; curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: installing rabbitmq 
  ansible.builtin.dnf: 
    name: rabbitmq-server
    state: present

- name: starting  and enabling rabbitmq
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: create rabbitmq user
  ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123

- name: set permissions
  ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"