- name: disabling mysql 
  ansible.builtin.shell: dnf module disable mysql -y

- name: copying mysql repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo 

- name: installing redis 
  ansible.builtin.dnf: 
    name: mysql-community-server
    state: present

- name: start and enable mysql
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: setup root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1