- name: nodejs setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs-setup

- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: Install dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /app

- name: systemd setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup