- name: creating the user 
  ansible.builtin.user:
    name: roboshop

- name: creating directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: downloading and unzipping
  ansible.builtin.unarchive:
    src: https://roboshop-builds.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: true