- name: python setup
  ansible.builtin.import_role:
    name: common
    tasks_from: python-setup

- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: Install dependencies
  ansible.builtin.command: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: systemd setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup